import Head from 'next/head'
import Link from 'next/link'
import { Button } from '../components/Button';
import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="avia">
          <Button>Go to search</Button>
        </Link>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
